
development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: Andre
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5
  username: Andre
  password:
  
